name: Generate Documentation

on:
  push:
    branches: [ docs/documentation_doxygen ]  # Ou a branch que será usada(provavelmente a main)

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen docs
      run: |
        doxygen Doxyfile
        mv docs/html/* docs/  # Organiza a saída


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs