name: Generate Documentation

on:
  push:
    branches: [ docs/documentation_doxygen ]  # Ou a branch que será usada(provavelmente a main)

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen docs
      run: |
        doxygen Doxyfile
        mv docs/html/* docs/  # Organiza a saída


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DEPLOY_TOKEN }}  # Substitui GITHUB_TOKEN pelo PAT
        publish_dir: ./docs
        keep_files: false  # Limpa arquivos antigos
        external_repository: pcgomesp/AEB-SWT2-Final-Project  # Repo original
        publish_branch: gh-pages  # Branch específica para docs