name: Generate Documentation and Deploy GitHub Pages

on:
  push:
    branches: [ "docs/pages" ]  # Ou a branch desejada

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Doxygen docs
      run: |
        doxygen Doxyfile
        mkdir -p docs/doxygen
        mv docs/html/* docs/doxygen/

    - name: Download LCOV coverage artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
        path: docs/lcov  # Aqui vai para docs/lcov

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_dir: ./docs
